#!/bin/bash

whoami
w
last
uname -a
hostname
uptime


sudo groupadd developers
sudo groupadd qa


sudo useradd -m -g developers aman
sudo useradd -m -g developers ritu
sudo useradd -m -g qa karan


id aman
id karan


pkill -u ritu
sudo userdel -r ritu
id ritu